Task1
GlanceFromTheScreen/ComputerGraphics pull request #1
Opened 2024-02-11 09:43 UTC by GlanceFromTheScreen

2024-02-11 19:21 UTC, anthark requested changes
Потерялся файл ресурсов WindowsProject1.rc при коммите

2024-02-11 19:25 UTC, GlanceFromTheScreen commented
Согласен, зря добавил его в gitignore. Теперь исправил этот недочет.

2024-02-11 19:33 UTC, anthark requested changes
А теперь не линкуется =( Поскольку dxgi.lib и d3d11.lib в настройках линковщика нет

2024-02-12 07:20 UTC, GlanceFromTheScreen commented
Пообщался с ребятами - говорят, что это из-за того, что я собираю под win32. Поменял в компановщике данный параметр на x64. По идее, должно заработать.

2024-02-12 12:20 UTC, anthark requested changes
Вы не тот файл закоммитили =) .vs и .suo файлы - это временные которые студия создает, их вообще не надо отдавать. Настройки проекта хранятся в .vcxproj

2024-02-12 16:02 UTC, GlanceFromTheScreen commented
Так, я понял в каком месте это должно фигурировать и как это изменить. Добавил данные файлы в конфигурации debug x64 и release x64. Изменения отразились в .vcxproj. Теперь должно заработать :)

2024-02-12 19:49 UTC, anthark approved these changes
Да, теперь взлетело. Засчитал =)

2024-02-12 19:49 UTC, merged